use serde::{Deserialize, Serialize};

/// GPU architecture type for classification.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum ArchClass {
    /// Consumer gaming GPU (NVIDIA GeForce / AMD Radeon)
    GamingGpu,
    /// Compute-focused mining card (CMP 170HX, etc.)
    ComputeCard,
    /// Datacenter GPU (A100, H100, etc.)
    DatacenterGpu,
    /// Consumer CPU
    Cpu,
}

/// Memory technology type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum MemoryType {
    Gddr6,
    Gddr6x,
    Gddr7,
    Hbm2,
    Hbm2e,
    Hbm3,
    Ddr4,
    Ddr5,
}

/// Detailed GPU architecture specification.
///
/// ALL VALUES ARE MODELED / NOT HARDWARE VERIFIED unless explicitly stated otherwise.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GpuArchitecture {
    pub name: String,
    pub arch_class: ArchClass,
    pub vendor: GpuVendor,
    pub compute_units: usize,
    pub threads_per_cu: usize,
    pub wavefront_size: usize,
    pub max_threads_per_cu: usize,
    pub register_file_per_cu_kb: f64,
    pub shared_memory_per_cu_kb: f64,
    pub l1_cache_per_cu_kb: f64,
    pub l2_cache_kb: f64,
    pub memory_type: MemoryType,
    pub memory_bus_width_bits: usize,
    pub memory_bandwidth_gb_s: f64,
    pub base_clock_mhz: f64,
    pub boost_clock_mhz: f64,
    pub fp32_tflops: f64,
    pub int32_ops_per_clock: usize,
    pub tdp_watts: f64,
    pub approximate_price_usd: f64,
    pub subgroup_native_size: usize,
    pub has_native_shuffle: bool,
    pub has_native_reduce: bool,
    pub year: u16,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum GpuVendor {
    Nvidia,
    Amd,
    Intel,
}

/// Creates the architecture database for modeling.
///
/// ALL VALUES ARE MODELED / NOT HARDWARE VERIFIED.
pub fn create_architecture_database() -> Vec<GpuArchitecture> {
    vec![
        // === GAMING GPUs ===
        GpuArchitecture {
            name: "RTX 3060".to_string(),
            arch_class: ArchClass::GamingGpu,
            vendor: GpuVendor::Nvidia,
            compute_units: 28, // SMs
            threads_per_cu: 128,
            wavefront_size: 32,
            max_threads_per_cu: 1536,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 100.0,
            l1_cache_per_cu_kb: 128.0,
            l2_cache_kb: 3072.0,
            memory_type: MemoryType::Gddr6,
            memory_bus_width_bits: 192,
            memory_bandwidth_gb_s: 360.0,
            base_clock_mhz: 1320.0,
            boost_clock_mhz: 1777.0,
            fp32_tflops: 12.74,
            int32_ops_per_clock: 1,
            tdp_watts: 170.0,
            approximate_price_usd: 329.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2021,
        },
        GpuArchitecture {
            name: "RTX 3070".to_string(),
            arch_class: ArchClass::GamingGpu,
            vendor: GpuVendor::Nvidia,
            compute_units: 46,
            threads_per_cu: 128,
            wavefront_size: 32,
            max_threads_per_cu: 1536,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 100.0,
            l1_cache_per_cu_kb: 128.0,
            l2_cache_kb: 4096.0,
            memory_type: MemoryType::Gddr6,
            memory_bus_width_bits: 256,
            memory_bandwidth_gb_s: 448.0,
            base_clock_mhz: 1500.0,
            boost_clock_mhz: 1725.0,
            fp32_tflops: 20.31,
            int32_ops_per_clock: 1,
            tdp_watts: 220.0,
            approximate_price_usd: 499.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2020,
        },
        GpuArchitecture {
            name: "RTX 4070".to_string(),
            arch_class: ArchClass::GamingGpu,
            vendor: GpuVendor::Nvidia,
            compute_units: 46,
            threads_per_cu: 128,
            wavefront_size: 32,
            max_threads_per_cu: 1536,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 100.0,
            l1_cache_per_cu_kb: 128.0,
            l2_cache_kb: 36864.0,
            memory_type: MemoryType::Gddr6x,
            memory_bus_width_bits: 192,
            memory_bandwidth_gb_s: 504.0,
            base_clock_mhz: 1920.0,
            boost_clock_mhz: 2475.0,
            fp32_tflops: 29.15,
            int32_ops_per_clock: 1,
            tdp_watts: 200.0,
            approximate_price_usd: 599.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2023,
        },
        GpuArchitecture {
            name: "RTX 5070".to_string(),
            arch_class: ArchClass::GamingGpu,
            vendor: GpuVendor::Nvidia,
            compute_units: 48,
            threads_per_cu: 128,
            wavefront_size: 32,
            max_threads_per_cu: 1536,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 100.0,
            l1_cache_per_cu_kb: 128.0,
            l2_cache_kb: 49152.0,
            memory_type: MemoryType::Gddr7,
            memory_bus_width_bits: 192,
            memory_bandwidth_gb_s: 672.0,
            base_clock_mhz: 2162.0,
            boost_clock_mhz: 2512.0,
            fp32_tflops: 32.0,
            int32_ops_per_clock: 1,
            tdp_watts: 250.0,
            approximate_price_usd: 549.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2025,
        },
        GpuArchitecture {
            name: "RX 6700 XT".to_string(),
            arch_class: ArchClass::GamingGpu,
            vendor: GpuVendor::Amd,
            compute_units: 40,
            threads_per_cu: 64,
            wavefront_size: 32,
            max_threads_per_cu: 2048,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 64.0,
            l1_cache_per_cu_kb: 32.0,
            l2_cache_kb: 3072.0,
            memory_type: MemoryType::Gddr6,
            memory_bus_width_bits: 192,
            memory_bandwidth_gb_s: 384.0,
            base_clock_mhz: 2321.0,
            boost_clock_mhz: 2581.0,
            fp32_tflops: 13.21,
            int32_ops_per_clock: 1,
            tdp_watts: 230.0,
            approximate_price_usd: 479.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2021,
        },
        GpuArchitecture {
            name: "RX 7700 XT".to_string(),
            arch_class: ArchClass::GamingGpu,
            vendor: GpuVendor::Amd,
            compute_units: 54,
            threads_per_cu: 64,
            wavefront_size: 32,
            max_threads_per_cu: 2048,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 64.0,
            l1_cache_per_cu_kb: 32.0,
            l2_cache_kb: 4096.0,
            memory_type: MemoryType::Gddr6,
            memory_bus_width_bits: 192,
            memory_bandwidth_gb_s: 432.0,
            base_clock_mhz: 1700.0,
            boost_clock_mhz: 2544.0,
            fp32_tflops: 17.08,
            int32_ops_per_clock: 1,
            tdp_watts: 245.0,
            approximate_price_usd: 449.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2023,
        },
        GpuArchitecture {
            name: "RX 7800 XT".to_string(),
            arch_class: ArchClass::GamingGpu,
            vendor: GpuVendor::Amd,
            compute_units: 60,
            threads_per_cu: 64,
            wavefront_size: 32,
            max_threads_per_cu: 2048,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 64.0,
            l1_cache_per_cu_kb: 32.0,
            l2_cache_kb: 4096.0,
            memory_type: MemoryType::Gddr6,
            memory_bus_width_bits: 256,
            memory_bandwidth_gb_s: 624.0,
            base_clock_mhz: 1295.0,
            boost_clock_mhz: 2430.0,
            fp32_tflops: 18.66,
            int32_ops_per_clock: 1,
            tdp_watts: 263.0,
            approximate_price_usd: 499.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2023,
        },
        // === COMPUTE/MINING CARDS ===
        GpuArchitecture {
            name: "CMP 170HX".to_string(),
            arch_class: ArchClass::ComputeCard,
            vendor: GpuVendor::Nvidia,
            compute_units: 108,
            threads_per_cu: 64,
            wavefront_size: 32,
            max_threads_per_cu: 2048,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 164.0,
            l1_cache_per_cu_kb: 192.0,
            l2_cache_kb: 8192.0,
            memory_type: MemoryType::Hbm2e,
            memory_bus_width_bits: 4096,
            memory_bandwidth_gb_s: 1493.0,
            base_clock_mhz: 1140.0,
            boost_clock_mhz: 1410.0,
            fp32_tflops: 0.0, // FP32 intentionally disabled
            int32_ops_per_clock: 1,
            tdp_watts: 250.0,
            approximate_price_usd: 3000.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2021,
        },
        GpuArchitecture {
            name: "CMP 100-210".to_string(),
            arch_class: ArchClass::ComputeCard,
            vendor: GpuVendor::Nvidia,
            compute_units: 80,
            threads_per_cu: 64,
            wavefront_size: 32,
            max_threads_per_cu: 2048,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 96.0,
            l1_cache_per_cu_kb: 128.0,
            l2_cache_kb: 6144.0,
            memory_type: MemoryType::Hbm2,
            memory_bus_width_bits: 4096,
            memory_bandwidth_gb_s: 900.0,
            base_clock_mhz: 1312.0,
            boost_clock_mhz: 1530.0,
            fp32_tflops: 15.7,
            int32_ops_per_clock: 1,
            tdp_watts: 250.0,
            approximate_price_usd: 2000.0,
            subgroup_native_size: 32,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2020,
        },
        GpuArchitecture {
            name: "BC-160".to_string(),
            arch_class: ArchClass::ComputeCard,
            vendor: GpuVendor::Amd,
            compute_units: 40,
            threads_per_cu: 64,
            wavefront_size: 32,
            max_threads_per_cu: 2048,
            register_file_per_cu_kb: 256.0,
            shared_memory_per_cu_kb: 64.0,
            l1_cache_per_cu_kb: 32.0,
            l2_cache_kb: 4096.0,
            memory_type: MemoryType::Hbm2,
            memory_bus_width_bits: 4096,
            memory_bandwidth_gb_s: 512.0,
            base_clock_mhz: 1100.0,
            boost_clock_mhz: 1375.0,
            fp32_tflops: 7.04,
            int32_ops_per_clock: 1,
            tdp_watts: 150.0,
            approximate_price_usd: 1500.0,
            subgroup_native_size: 64,
            has_native_shuffle: true,
            has_native_reduce: true,
            year: 2021,
        },
        // === REFERENCE CPU ===
        GpuArchitecture {
            name: "Desktop CPU (Zen 4)".to_string(),
            arch_class: ArchClass::Cpu,
            vendor: GpuVendor::Amd,
            compute_units: 8,
            threads_per_cu: 1,
            wavefront_size: 1,
            max_threads_per_cu: 2,
            register_file_per_cu_kb: 0.5,
            shared_memory_per_cu_kb: 32.0, // L1 data cache
            l1_cache_per_cu_kb: 32.0,
            l2_cache_kb: 8192.0,
            memory_type: MemoryType::Ddr5,
            memory_bus_width_bits: 64,
            memory_bandwidth_gb_s: 51.2,
            base_clock_mhz: 4500.0,
            boost_clock_mhz: 5700.0,
            fp32_tflops: 0.18,
            int32_ops_per_clock: 4,
            tdp_watts: 105.0,
            approximate_price_usd: 300.0,
            subgroup_native_size: 1,
            has_native_shuffle: false,
            has_native_reduce: false,
            year: 2023,
        },
    ]
}
